ch5/with-rails/config/routes.rb
# frozen_string_literal: true

Voting::Application.routes.draw do
  resources :votes

  scope 'api/ratings' do
    constraints(accept: 'application/vnd.pauldix.voteservice-v1+json') do
      controller :votes do
        # put '/entries/:entry_id/users/:user_id/vote', :to => 'create'
        get '/users/:user_id/up', to: 'entry_ids_voted_up_for_user'
        # get '/users/:user_id/down', :to => 'entry_ids_voted_down_for_user'
        # get '/entries/totals', :to => 'totals_for_entries'
        # get '/users/:user_id/votes', :to => 'votes_for_users'
        # get '/users/:user_id/totals', :to => 'totals_for_user'
      end
    end
  end
end

ch5/with-rails/app/models/vote.rb
# frozen_string_literal: true

class Vote < ActiveRecord::Base
end

ch5/with-rails/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
end

ch5/with-rails/app/controllers/votes_controller.rb
# frozen_string_literal: true

class VotesController < ApplicationController
  def entry_ids_voted_down_for_user; end

  # GET /votes
  # GET /votes.xml
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.xml
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.xml
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.xml
  def create
    @vote = Vote.new(params[:vote])

    respond_to do |format|
      if @vote.save
        format.html { redirect_to(@vote, notice: 'Vote was successfully created.') }
        format.xml  { render xml: @vote, status: :created, location: @vote }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.xml
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to(@vote, notice: 'Vote was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.xml
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to(votes_url) }
      format.xml  { head :ok }
    end
  end
end

ch5/with-rails/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

ch5/with-rails/app/helpers/votes_helper.rb
# frozen_string_literal: true

module VotesHelper
end

ch5/with-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voting</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

ch5/with-rails/app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry_id %><br />
    <%= f.text_field :entry_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ch5/with-rails/app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

ch5/with-rails/app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Entry</th>
    <th>User</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.entry_id %></td>
    <td><%= vote.user_id %></td>
    <td><%= vote.value %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

ch5/with-rails/app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

ch5/with-rails/app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Entry:</b>
  <%= @vote.entry_id %>
</p>

<p>
  <b>User:</b>
  <%= @vote.user_id %>
</p>

<p>
  <b>Value:</b>
  <%= @vote.value %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>